### PR TITLE
reversible reactions finished

### PR DESCRIPTION
**Pull request by Gedichter**

### CODE REVIEW

**Comment by Gedichter** [comment]
Sorry I forgot to add the file. Just added.

**Comment by hsim13372** [comment]
But it still failed the tests...

**Comment by Gedichter** [comment]
I didn't change the test file.....But you should be able to see the result when you run crude_interface. 
Or do you mean David has offered some file to check if the computation is correct?

**Comment by hsim13372** [comment]
I mean did you run pytest before making this pull request?

**Comment by Gedichter** [comment]
Actually no.... I didn't change the test file to adapt to the code after the change.....

**Pull request merged**
